### ISSUE TITLE
Validation not ignoring big value sets

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2542]
Alaina is validating the Vital Records messages in TCAMT. She is getting ICD-10 errors. This is one of the value sets that are currently highlighted in IGAMT "This table has too many codes (more than 1000), so it will be ignored".  

The validation is not ignoring this value set and is generating these errors. They should be excluded from the validation.

OBX_VR_CCOD-CoConstraint-14-2 - [CoConstraint-14-2]If the value of OBX-3[1] (CWE) is '80356-9','then the value of OBX-5[1] (varies) should be one of codes in PHVS_CauseOfDeath_ICD-10_CDC' .

**Comment by smartinez290** [comment]
@Jungyubw is this issue going to be solved by the next deployment?

**Comment by Jungyubw** [comment]
@smartinez290 
I fixed this and I am doing QA. It should be included to next deployment.
Thanks.

**Comment by Jungyubw** [comment]
Done

**Comment by smartinez290** [comment]
I just checked the validation, they are still showing as errors.

![image](https://user-images.githubusercontent.com/14842422/31950770-587e9d08-b8aa-11e7-8ad0-3ecfa72fd986.png)

**Comment by Jungyubw** [comment]
I will stop by your office.

2017. 10. 24. 오전 10:59에 "smartinez290" <notifications@github.com>님이 작성:

**Comment by smartinez290** [comment]
@Jungyubw I am working from home. I show you this one tomorrow or just push HL7 Version 2.6 Implementation Guide-Vital Records Death Reporting, Release 1 - US Realm  in dev server the CCOD_A04 profile. and use the following message:

MSH|^~\&|DRrcv^2.16.840.1.113883.3.20091^ISO|NCHS^2.16.840.1.113883.3.8989^ISO|CauseOfDeathProcessing^2.16.840.1.113883.3.20091^ISO|VRDept^2.16.840.1.113883.3.20091^ISO|20101102133312-0400||ADT^A04^ADT_A01|1223334499|P|2.6|||AL|NE|US||||CCODA04_V1.0^PHIN VS
EVN||20101102133312
PID|1||900213^^^&2.16.840.1.113883.4.1&ISO^DC||Smith^Josephine^Madeline^^^^L||||||||||||||||||||||||201011021400-0500|Y|
PV1||N
OBX|1|CWE|80356-9^Cause of death entity axis code [Automated]^LN|1|I269^Pulmonary embolism^I10C||||||F
OBX|2|NM|PHC1428^Part\Line Number^CDCPHINVS|1|1||||||F
OBX|3|NM|PHC1427^Sequence within Line^CDCPHINVS|1|1||||||F
OBX|4|CWE|80356-9^Cause of death entity axis code [Automated]^LN|2|I269^Deep Vein Thrombosis^I10C||||||F
OBX|5|NM|PHC1428^Part\Line Number^CDCPHINVS|2|2||||||F
OBX|6|NM|PHC1427^Sequence within Line^CDCPHINVS|2|1||||||F
OBX|7|CWE|80356-9^Cause of death entity axis code [Automated]^LN|3|L930^Lupus^I10C||||||F
OBX|8|NM|PHC1428^Part\Line Number^CDCPHINVS|3|3||||||F
OBX|9|NM|PHC1427^Sequence within Line^CDCPHINVS|3|1||||||F
OBX|10|CWE|80357-7^Cause of death record axis code [Automated]^LN|1|I269^Pulmonary embolism^I10C||||||F
OBX|11|CWE|80357-7^Cause of death record axis code [Automated]^LN|2|I269^Deep Vein Thrombosis^I10C||||||F
OBX|12|CWE|80357-7^Cause of death record axis code [Automated]^LN|3|L^Lupus^I10C||||||F
OBX|13|CWE|80358-5^Cause of death.underlying [Automated]^LN||""||||||F
OBX|14|CWE|80359-3^Cause of death.underlying [Manual]^LN||L930^Lupus^I10C||||||F
OBX|15|CWE|69443-0^ Did Tobacco Use Contribute to Death^LN||373067005^No^SCT||||||F
OBX|16|CWE|80626-5^Activity at time of death^LN||PHC1350^During unspecified activity^CDCPHINVS||||||F
OBX|17|CWE|69449-7^Manner of Death^LN||38605008^Natural Death^SCT||||||F
OBX|18|CWE|PHC1461^Intentional Reject Edit Flag^CDCPHINVS||PHC1370^Duration Error Line 1 \T\ 2^CDCPHINVS||||||F

**Comment by smartinez290** [comment]
@Jungyubw I discussed this issue with Hossam and he said that this issue should go away when the new co-constraints requirements are implemented. I need to show you exactly what I mean. Could you please stop by my office?

**Comment by Jungyubw** [comment]
Fixed

**Comment by smartinez290** [comment]
@Jungyubw Why am I getting now these errors in TCMAT Context-Free Validation and different errors in GVT when pushing from IGAMT?

![image](https://user-images.githubusercontent.com/14842422/32281051-0db1db0a-bef4-11e7-9d16-129db06fcb47.png)


From IGAMT to GVT validation
![image](https://user-images.githubusercontent.com/14842422/32281104-40299c44-bef4-11e7-9243-32b59c676da4.png)

**Comment by smartinez290** [comment]
Ignore the "Code Not Found" error, it is an extra space. Just look the ICD10 errors.

**Comment by Jungyubw** [comment]
This is version issue. I am deploying TCAMT, please try it again after my deploy. I will let you know
On Nov 1, 2017, at 11:03 AM, smartinez290 <notifications@github.com<mailto:notifications@github.com>> wrote:


@Jungyubw<https://github.com/jungyubw> Why am I getting now these errors in TCMAT Context-Free Validation and different errors in GVT when pushing from IGAMT?

[image]<https://user-images.githubusercontent.com/14842422/32281051-0db1db0a-bef4-11e7-9d16-129db06fcb47.png>

From IGAMT to GVT validation
[image]<https://user-images.githubusercontent.com/14842422/32281104-40299c44-bef4-11e7-9243-32b59c676da4.png>

**Comment by smartinez290** [comment]
Woo -- I am still getting errors in TCAMT and also GVT when pushed from IGAMT.

![image](https://user-images.githubusercontent.com/14842422/32462915-1ebe5e1e-c309-11e7-9078-3db05ac66f5d.png)
