### ISSUE TITLE
Unable to save or delete "single code" constraint after modification

### ISSUE THREAD

**Issue by carolinerosin** [haffonist/igamt#2704]
Here's what I did:
- create a flavor of a segment (MSH_ACK), based on another flavor (MSH_LRI). My MSH_LRI had some "single code" constraints
- in my new flavor, I want to change the values in the single code constraints, so I open the tree element and clic on the little pencil in the valueSet/singleCode column
- I change the code value to another value in the editor
- the save button stays greyed out, so I cannot save

I thought I could delete (in the tree view) to re-create, but when I clic on the little cross button, nothing happens (it is not deleted).
I can only delete in the editor.

**Comment by smartinez290** [comment]
It is happening to me also. I just ran the test.

**Comment by smartinez290** [comment]
@carolinerosin I just checked this again and it looks like is working. It looks like it was fixed. Pls. take a look,

**Comment by carolinerosin** [comment]
@smartinez290 still having the same issue, Save button stays greyed out even if I change the value, so I cannot save my changes (I tried on production, tool version 2.0.0-beta13)

**Comment by smartinez290** [comment]
@carolinerosin it looks like you have to search for the value set where the code is again, select the value set and choose the code, then the save button will be activated. I don't think we should go through all this, since a single code was already selected. Is like doing it all over again.

**Comment by carolinerosin** [comment]
For me, since I can change the text of the code or the code system (by typing), any change in these two text fields should activate the save button. 
If the workflow if to go through the whole process (select value set and select code), then the text boxes shouldn't be editable in the first place.

**Comment by afrold** [comment]
@Jungyubw please fix this ASAP.

**Comment by Jungyubw** [comment]
I will fix it today

2018. 1. 4. 오전 10:30에 "Harold Affo" <notifications@github.com>님이 작성:

**Comment by Jungyubw** [comment]
Fixed
