### ISSUE TITLE
Exporting Guide as Word Document - Co-constraint table not displayed

### ISSUE THREAD

**Issue by smartinez290** [haffonist/igamt#2772]
Per Dave": When I export the guide to a Word Document, most things look like the HTML, but the OBX co-constraints table doesn't work at all.  There are many pages with only an "IF THEN" at the top and the rest of the page is blank, see below."
 
![image](https://user-images.githubusercontent.com/14842422/35696029-2f6f0b7a-0754-11e8-9bf4-6654cf28faaa.png)

@Abdelghani90 find out the following:
When I export it as HTML, it works as expected.
When I export in Verbose mode for Co-Constraint it works as expected for both word and HTML.
When I export as word and my configuration is set to Compact (for Co constraint always). The document is exported but the co-constraint  table is not displayed.

I also checked a different IG and this is not happening.

**Comment by afrold** [comment]
@maxence-lefort  ?

**Comment by smartinez290** [comment]
@maxence-lefort does the latest deployment supposed to fix this issue. I am testing in IGAMTdev and now the world export is exporting only until section 4. Nothing after section 4 is in the document.

**Comment by maxence-lefort** [comment]
@smartinez290 I just pushed a new fix, we will let you know when it's deployed so that you can test again

**Comment by smartinez290** [comment]
@maxence-lefort @haffonist told me to test it today. I just did, and it is still not working.
